### ISSUE TITLE
Error with room.sendTo()

### ISSUE THREAD

**Issue by aitorjs** [ipfs-labs/ipfs-pubsub-room-demo#9]
I try the demo without any change and when the code calls to room.sendTo(), I get this error: _this._ipfs._libp2pNode.dialProtocol is not a function_ on connection.js line 51. This function is [this](https://github.com/libp2p/js-libp2p#libp2pdialprotocolpeer-protocol-callback) 

   I'm on node 9.2.0 and npm 6.0.1. ¿Any ideas why I get this error? Thanks! :-)

**Comment by pgte** [comment]
What js-IPFS version are you using?

**Comment by aitorjs** [comment]
Thanks for the fast reply! :-)

v0.27.7. I see that are more recent versions. I'll try with the last one, v0.29.1

**Comment by aitorjs** [comment]
Updating IPFS to v0.29.1 error disappear and the room.sendTo() is running. :-)

Thanks for all! Amazing job team! Keep in that way! :-D
